# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1371959dbee17fc21524415d96cec318e7815da5bc358d681b2f085d25b15b93b8964ecc0ce97b3d83611ee947ae32590e3879cb849927ee5467c0d32f945c
  s3_secret_key: 6i176gVCELAUKlTBwkSZYH1MwDWoJ/yLv8RhEObI
  s3_access_key: AKIAJJJCAC6XREJHS3QQ
  stripe_secret_key: sk_test_jopOV6pvjXs8PLPfnJKy7iYG
  stripe_public_key: pk_test_kxWcRexeCqiilkBq4Jj1UiQE

test:
  secret_key_base: d16f4fc1ff3c2d67cb402ab375aa776bfa9164554fe7eeef9c2aab8990aa4205a90f454668643a87126af4f6a8cfaf850a0684cd807eba3c91bf27b6f967badc
  s3_secret_key: 6i176gVCELAUKlTBwkSZYH1MwDWoJ/yLv8RhEObI
  s3_access_key: AKIAJJJCAC6XREJHS3QQ
  stripe_secret_key: sk_test_jopOV6pvjXs8PLPfnJKy7iYG
  stripe_public_key: pk_test_kxWcRexeCqiilkBq4Jj1UiQE

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: sk_test_jopOV6pvjXs8PLPfnJKy7iYG
  stripe_public_key: pk_test_kxWcRexeCqiilkBq4Jj1UiQE